// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh218QFwwxJypdVfy7-SBUEWOGsRf1Nf8',
    appId: '1:544717444928:web:6366eba8668caeff6e0ca5',
    messagingSenderId: '544717444928',
    projectId: 'planova-18b2d',
    authDomain: 'planova-18b2d.firebaseapp.com',
    storageBucket: 'planova-18b2d.firebasestorage.app',
    measurementId: 'G-N5K5DGCNXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfZvbCL_2BfNHTPEJ3SU_K7Xj65PVP34',
    appId: '1:544717444928:android:4ea3c87b1fcd5f726e0ca5',
    messagingSenderId: '544717444928',
    projectId: 'planova-18b2d',
    storageBucket: 'planova-18b2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VGG3B4UUkPbHMH58wDs18dDJ-KLvFtc',
    appId: '1:544717444928:ios:4eccbd9006055b036e0ca5',
    messagingSenderId: '544717444928',
    projectId: 'planova-18b2d',
    storageBucket: 'planova-18b2d.firebasestorage.app',
    iosBundleId: 'com.example.planovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VGG3B4UUkPbHMH58wDs18dDJ-KLvFtc',
    appId: '1:544717444928:ios:4eccbd9006055b036e0ca5',
    messagingSenderId: '544717444928',
    projectId: 'planova-18b2d',
    storageBucket: 'planova-18b2d.firebasestorage.app',
    iosBundleId: 'com.example.planovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh218QFwwxJypdVfy7-SBUEWOGsRf1Nf8',
    appId: '1:544717444928:web:28d26ec29e5f66056e0ca5',
    messagingSenderId: '544717444928',
    projectId: 'planova-18b2d',
    authDomain: 'planova-18b2d.firebaseapp.com',
    storageBucket: 'planova-18b2d.firebasestorage.app',
    measurementId: 'G-F7T9936HG9',
  );
}
